"""empty message

Revision ID: 372e7eb1fea3
Revises: 9e8a619e75bf
Create Date: 2025-11-09 12:53:26.219883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '372e7eb1fea3'
down_revision: Union[str, Sequence[str], None] = '9e8a619e75bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('meeting_datetime', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_meetings_meeting_date'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_time'), table_name='meetings')
    op.create_index(op.f('ix_meetings_meeting_datetime'), 'meetings', ['meeting_datetime'], unique=True)
    op.drop_column('meetings', 'meeting_date')
    op.drop_column('meetings', 'meeting_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('meeting_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('meetings', sa.Column('meeting_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_meetings_meeting_datetime'), table_name='meetings')
    op.create_index(op.f('ix_meetings_meeting_time'), 'meetings', ['meeting_time'], unique=True)
    op.create_index(op.f('ix_meetings_meeting_date'), 'meetings', ['meeting_date'], unique=True)
    op.drop_column('meetings', 'meeting_datetime')
    # ### end Alembic commands ###
