"""Initial database schema

Revision ID: 30c145fd0efb
Revises: 
Create Date: 2025-11-08 20:16:34.217703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c145fd0efb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('content_format', sa.Enum('PDF', 'HTML', 'CSV', 'TEXT', name='contentformat'), nullable=False),
    sa.Column('converted_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_index(op.f('ix_documents_url'), 'documents', ['url'], unique=True)
    op.create_table('legislation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_number', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('legislation_type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('APPROVED', 'REJECTED', 'CONTINUED', 'WITHDRAWN', 'PENDING', name='legislationstatus'), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislation_file_number'), 'legislation', ['file_number'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.DateTime(), nullable=False),
    sa.Column('meeting_type', sa.Enum('REGULAR', 'SPECIAL', 'COMMITTEE', name='meetingtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_meeting_date'), 'meetings', ['meeting_date'], unique=True)
    op.create_table('officials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('official_type', sa.Enum('SUPERVISOR', 'MAYOR', name='officialtype'), nullable=False),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('initials', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officials_name'), 'officials', ['name'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislation_id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('VOTE', 'SPONSOR', 'CO_SPONSOR', 'PROPOSE', name='actiontype'), nullable=False),
    sa.Column('vote', sa.Enum('AYE', 'NO', 'ABSTAIN', 'ABSENT', 'EXCUSED', name='votetype'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['official_id'], ['officials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_legislation_id'), 'actions', ['legislation_id'], unique=False)
    op.create_index(op.f('ix_actions_meeting_id'), 'actions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_actions_official_id'), 'actions', ['official_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actions_official_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_meeting_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_legislation_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_officials_name'), table_name='officials')
    op.drop_table('officials')
    op.drop_index(op.f('ix_meetings_meeting_date'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_legislation_file_number'), table_name='legislation')
    op.drop_table('legislation')
    op.drop_index(op.f('ix_documents_url'), table_name='documents')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
