"""empty message

Revision ID: 3b953b8de0dd
Revises: 372e7eb1fea3
Create Date: 2025-11-09 13:00:18.726138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b953b8de0dd'
down_revision: Union[str, Sequence[str], None] = '372e7eb1fea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'meeting_type',
               existing_type=postgresql.ENUM('REGULAR', 'SPECIAL', 'COMMITTEE', name='meetingtype'),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'meeting_type',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('REGULAR', 'SPECIAL', 'COMMITTEE', name='meetingtype'),
               existing_nullable=False)
    # ### end Alembic commands ###
