"""empty message

Revision ID: 9e8a619e75bf
Revises: 0001add_metadata
Create Date: 2025-11-09 12:42:00.672006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8a619e75bf'
down_revision: Union[str, Sequence[str], None] = '0001add_metadata'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('meeting_file_number', sa.String(length=255), nullable=True))
    op.add_column('meetings', sa.Column('meeting_time', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_meetings_meeting_file_number'), 'meetings', ['meeting_file_number'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_time'), 'meetings', ['meeting_time'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_meeting_time'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_file_number'), table_name='meetings')
    op.drop_column('meetings', 'meeting_time')
    op.drop_column('meetings', 'meeting_file_number')
    # ### end Alembic commands ###
