"""empty message

Revision ID: 14f60836fd82
Revises: c0a7b6d2edc5
Create Date: 2025-11-09 13:20:38.225491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f60836fd82'
down_revision: Union[str, Sequence[str], None] = 'c0a7b6d2edc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_meeting_datetime'), table_name='meetings')
    op.create_index(op.f('ix_meetings_meeting_datetime'), 'meetings', ['meeting_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_meeting_datetime'), table_name='meetings')
    op.create_index(op.f('ix_meetings_meeting_datetime'), 'meetings', ['meeting_datetime'], unique=True)
    # ### end Alembic commands ###
