"""empty message

Revision ID: a04311838dcc
Revises: 445b48d2a57d
Create Date: 2025-11-09 13:55:16.367042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04311838dcc'
down_revision: Union[str, Sequence[str], None] = '445b48d2a57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_meeting_file_number'), table_name='meetings')
    op.create_index(op.f('ix_meetings_meeting_file_number'), 'meetings', ['meeting_file_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_meeting_file_number'), table_name='meetings')
    op.create_index(op.f('ix_meetings_meeting_file_number'), 'meetings', ['meeting_file_number'], unique=False)
    # ### end Alembic commands ###
