"""empty message

Revision ID: 445b48d2a57d
Revises: 14f60836fd82
Create Date: 2025-11-09 13:51:25.001034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445b48d2a57d'
down_revision: Union[str, Sequence[str], None] = '14f60836fd82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'actions', 'meetings', ['meeting_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'meetings', ['meeting_id'], ['id'])
    op.add_column('meetings', sa.Column('meeting_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'meeting_title')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'actions', type_='foreignkey')
    # ### end Alembic commands ###
